import { useState } from "react";
import { ArrowDownToLine, ArrowRight, CheckCheck, LockKeyhole, MessageCircle, Mic, Phone, Send, ShieldCheck, Users, Video } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import InstallAppDialog from "@/components/chat/InstallAppDialog";
import buzzLogo from "@/assets/buzz-logo.jpeg";
import familyImage from "@/assets/buzz-family-call.jpg";
import groupImage from "@/assets/buzz-group-call.jpg";

type PublicPage = "features" | "privacy" | "buzz-web" | "download" | "contact";
export const publicPages: PublicPage[] = ["features", "privacy", "buzz-web", "download", "contact"];

const Preview = () => <div className="mx-auto w-full max-w-xl overflow-hidden rounded-md border border-border bg-card shadow-xl" aria-label="Buzz chat preview">
  <div className="flex items-center gap-3 border-b border-border px-4 py-3"><img src={buzzLogo} alt="Buzz" className="h-9 w-9 rounded-md object-cover" /><div className="flex-1"><strong className="text-sm">Ayesha</strong><p className="text-xs text-online">online</p></div><Video className="h-5 w-5 text-primary" /><Phone className="h-5 w-5 text-primary" /></div>
  <div className="space-y-4 bg-landing-canvas px-4 py-10"><p className="w-fit max-w-[85%] rounded-md bg-card px-4 py-3 text-sm shadow-sm">Hey! Are we meeting this evening?</p><p className="ml-auto w-fit max-w-[85%] rounded-md bg-landing-bubble px-4 py-3 text-sm shadow-sm">Yes, see you at 6! ☕ <CheckCheck className="inline h-3 w-3 text-primary" /></p><p className="w-fit rounded-md bg-card px-4 py-3 text-sm shadow-sm">I’ll bring everyone along 😊</p></div>
  <div className="flex items-center gap-3 border-t border-border px-4 py-3 text-muted-foreground"><MessageCircle className="h-4 w-4" /><span className="flex-1 text-sm">Message</span><Mic className="h-4 w-4" /></div>
</div>;

export default function BuzzPublicPage({ page, onLogin }: { page: PublicPage; onLogin: () => void }) {
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [message, setMessage] = useState("");
  const install = <InstallAppDialog trigger={<Button className="gradient-brand h-12 gap-2 px-6"><ArrowDownToLine className="h-4 w-4" /> Install Buzz</Button>} />;
  if (page === "contact") return <section className="mx-auto min-h-[70vh] max-w-5xl px-5 py-14 sm:py-24 low-fade"><p className="text-sm font-semibold text-primary">BUZZ SUPPORT</p><h1 className="mt-3 text-4xl sm:text-6xl">Contact Buzz</h1><p className="mt-5 max-w-xl text-muted-foreground">Questions or feedback? Write to us at <a className="underline text-primary" href="mailto:prasadprem904@gmail.com">prasadprem904@gmail.com</a>.</p><form className="mt-10 grid max-w-xl gap-5" onSubmit={e => { e.preventDefault(); window.location.href = `mailto:prasadprem904@gmail.com?subject=${encodeURIComponent(`Buzz contact from ${name}`)}&body=${encodeURIComponent(`${message}\n\nFrom: ${name}\nReply to: ${email}`)}`; }}><label className="grid gap-2 text-sm font-medium">Name<Input required value={name} onChange={e => setName(e.target.value)} placeholder="Your name" /></label><label className="grid gap-2 text-sm font-medium">Email<Input required type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@example.com" /></label><label className="grid gap-2 text-sm font-medium">Message<Textarea required minLength={10} value={message} onChange={e => setMessage(e.target.value)} placeholder="How can we help?" rows={6} /></label><p className="text-xs text-muted-foreground">This opens your email app with your message ready to send. In-page delivery is not available yet.</p><Button type="submit" className="w-fit gap-2 gradient-brand"><Send className="h-4 w-4" /> Open email app</Button></form></section>;
  if (page === "download") return <section className="mx-auto grid min-h-[70vh] max-w-6xl items-center gap-12 px-5 py-14 lg:grid-cols-2 lg:py-24 low-fade"><div className="order-2 lg:order-1"><Preview /></div><div className="order-1 lg:order-2"><img src={buzzLogo} alt="Buzz logo" className="h-20 w-20 rounded-md object-cover shadow-lg" /><h1 className="mt-7 text-4xl sm:text-6xl">Buzz on your device</h1><p className="my-6 max-w-md text-lg text-muted-foreground">Chat and call from your phone or desktop. Install Buzz for quick access from your home screen.</p>{install}<p className="mt-4 text-sm text-muted-foreground">If your browser doesn't offer direct installation, the install window shows the steps for your device.</p></div></section>;
  if (page === "privacy") return <><section className="bg-landing-night text-primary-foreground"><div className="mx-auto grid max-w-6xl items-center gap-12 px-5 py-16 lg:grid-cols-2 lg:py-24 low-fade"><div><ShieldCheck className="h-10 w-10 text-primary" /><h1 className="mt-6 text-4xl sm:text-6xl">Your conversations, your choice.</h1><p className="mt-6 max-w-lg text-lg text-primary-foreground/75">Buzz lets you connect with a username instead of sharing your phone number. Nearby chats use end-to-end encryption; regular messages and calls are protected in transit.</p><Button className="mt-8 gradient-brand" onClick={onLogin}>Open Buzz <ArrowRight className="ml-2 h-4 w-4" /></Button></div><Preview /></div></section><section className="mx-auto grid max-w-6xl gap-8 px-5 py-16 sm:grid-cols-3"><div><LockKeyhole className="text-primary" /><h2 className="mt-4 text-xl font-semibold">Control your profile</h2><p className="mt-2 text-muted-foreground">Choose who sees your activity, typing, and read receipts in Buzz settings.</p></div><div><ShieldCheck className="text-primary" /><h2 className="mt-4 text-xl font-semibold">Nearby privacy</h2><p className="mt-2 text-muted-foreground">Verify a nearby contact’s safety number before exchanging encrypted messages.</p></div><div><MessageCircle className="text-primary" /><h2 className="mt-4 text-xl font-semibold">No phone number</h2><p className="mt-2 text-muted-foreground">Find friends by username without publishing your number.</p></div></section></>;
  if (page === "buzz-web") return <><section className="mx-auto grid max-w-6xl items-center gap-12 px-5 py-16 lg:grid-cols-2 lg:py-24 low-fade"><div><p className="font-semibold text-primary">BUZZ WEB</p><h1 className="mt-4 text-4xl sm:text-6xl">Your conversations, on a bigger screen.</h1><p className="my-6 max-w-lg text-lg text-muted-foreground">Send messages, share files, and make voice or video calls directly in your browser.</p><Button onClick={onLogin} className="gradient-brand gap-2">Open Buzz Web <ArrowRight className="h-4 w-4" /></Button></div><Preview /></section><section className="bg-landing-night text-primary-foreground"><div className="mx-auto grid max-w-6xl items-center gap-10 px-5 py-16 md:grid-cols-2"><img src={familyImage} alt="Family video calling" className="mx-auto max-h-[420px] w-full max-w-sm rounded-md object-cover" /><div><Video className="h-8 w-8 text-primary" /><h2 className="mt-5 text-3xl sm:text-4xl">Make every call feel closer.</h2><p className="mt-4 text-primary-foreground/70">Start a voice or video call from any conversation in Buzz.</p></div></div></section></>;
  return <><section className="mx-auto grid max-w-6xl items-center gap-12 px-5 py-16 lg:grid-cols-2 lg:py-24 low-fade"><div><p className="font-semibold text-primary">BUZZ FEATURES</p><h1 className="mt-4 text-4xl sm:text-6xl">Stay close, your way.</h1><p className="my-6 max-w-lg text-lg text-muted-foreground">One place for chats, Moments, calls and the people that matter.</p><Button onClick={onLogin} className="gradient-brand gap-2">Start chatting <ArrowRight className="h-4 w-4" /></Button></div><Preview /></section><section className="bg-landing-night text-primary-foreground"><div className="mx-auto grid max-w-6xl gap-10 px-5 py-16 md:grid-cols-2"><img src={groupImage} alt="Friends enjoying a group conversation" className="aspect-video w-full rounded-md object-cover" /><div className="self-center"><Users className="text-primary" /><h2 className="mt-4 text-3xl">Together in every conversation</h2><p className="mt-4 text-primary-foreground/70">Create groups, share photos and files, and catch up with voice or video calls.</p></div></div></section><section className="mx-auto grid max-w-6xl gap-8 px-5 py-16 sm:grid-cols-3">{[[MessageCircle,"Private chats","Start a conversation by username."],[Video,"Voice & video","Call directly from a chat."],[ShieldCheck,"Moments & nearby","Share a Moment or connect nearby."]].map(([Icon,title,copy]) => <div key={title}><Icon className="text-primary" /><h2 className="mt-4 text-xl font-semibold">{title}</h2><p className="mt-2 text-muted-foreground">{copy}</p></div>)}</section></>;
}
